// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: test.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from test.proto</summary>
public static partial class SampleProtoGeneratedClassReflection {

  #region Descriptor
  /// <summary>File descriptor for test.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SampleProtoGeneratedClassReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cgp0ZXN0LnByb3RvInoKBFRlc3QSDAoEdHlwZRgBIAEoCRIPCgd2ZXJzaW9u",
          "GAIgASgFEhYKDmNvcnJlbGF0aW9uX2lkGAMgASgJEhQKDG9wZXJhdGlvbl9p",
          "ZBgEIAEoCRISCgptZXNzYWdlX2lkGAUgASgJEhEKCXRpbWVzdGFtcBgGIAEo",
          "CWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::SampleProtoGeneratedClass), global::SampleProtoGeneratedClass.Parser, new[]{ "Type", "Version", "CorrelationId", "OperationId", "MessageId", "Timestamp" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class SampleProtoGeneratedClass : pb::IMessage<SampleProtoGeneratedClass>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SampleProtoGeneratedClass> _parser = new pb::MessageParser<SampleProtoGeneratedClass>(() => new SampleProtoGeneratedClass());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SampleProtoGeneratedClass> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SampleProtoGeneratedClassReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SampleProtoGeneratedClass() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SampleProtoGeneratedClass(SampleProtoGeneratedClass other) : this() {
    type_ = other.type_;
    version_ = other.version_;
    correlationId_ = other.correlationId_;
    operationId_ = other.operationId_;
    messageId_ = other.messageId_;
    timestamp_ = other.timestamp_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SampleProtoGeneratedClass Clone() {
    return new SampleProtoGeneratedClass(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private string type_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Type {
    get { return type_; }
    set {
      type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "version" field.</summary>
  public const int VersionFieldNumber = 2;
  private int version_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Version {
    get { return version_; }
    set {
      version_ = value;
    }
  }

  /// <summary>Field number for the "correlation_id" field.</summary>
  public const int CorrelationIdFieldNumber = 3;
  private string correlationId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CorrelationId {
    get { return correlationId_; }
    set {
      correlationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "operation_id" field.</summary>
  public const int OperationIdFieldNumber = 4;
  private string operationId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string OperationId {
    get { return operationId_; }
    set {
      operationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "message_id" field.</summary>
  public const int MessageIdFieldNumber = 5;
  private string messageId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string MessageId {
    get { return messageId_; }
    set {
      messageId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "timestamp" field.</summary>
  public const int TimestampFieldNumber = 6;
  private string timestamp_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Timestamp {
    get { return timestamp_; }
    set {
      timestamp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SampleProtoGeneratedClass);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SampleProtoGeneratedClass other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (Version != other.Version) return false;
    if (CorrelationId != other.CorrelationId) return false;
    if (OperationId != other.OperationId) return false;
    if (MessageId != other.MessageId) return false;
    if (Timestamp != other.Timestamp) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type.Length != 0) hash ^= Type.GetHashCode();
    if (Version != 0) hash ^= Version.GetHashCode();
    if (CorrelationId.Length != 0) hash ^= CorrelationId.GetHashCode();
    if (OperationId.Length != 0) hash ^= OperationId.GetHashCode();
    if (MessageId.Length != 0) hash ^= MessageId.GetHashCode();
    if (Timestamp.Length != 0) hash ^= Timestamp.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Type);
    }
    if (Version != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Version);
    }
    if (CorrelationId.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(CorrelationId);
    }
    if (OperationId.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(OperationId);
    }
    if (MessageId.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(MessageId);
    }
    if (Timestamp.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Timestamp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Type);
    }
    if (Version != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Version);
    }
    if (CorrelationId.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(CorrelationId);
    }
    if (OperationId.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(OperationId);
    }
    if (MessageId.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(MessageId);
    }
    if (Timestamp.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Timestamp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
    }
    if (Version != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Version);
    }
    if (CorrelationId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CorrelationId);
    }
    if (OperationId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(OperationId);
    }
    if (MessageId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageId);
    }
    if (Timestamp.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Timestamp);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SampleProtoGeneratedClass other) {
    if (other == null) {
      return;
    }
    if (other.Type.Length != 0) {
      Type = other.Type;
    }
    if (other.Version != 0) {
      Version = other.Version;
    }
    if (other.CorrelationId.Length != 0) {
      CorrelationId = other.CorrelationId;
    }
    if (other.OperationId.Length != 0) {
      OperationId = other.OperationId;
    }
    if (other.MessageId.Length != 0) {
      MessageId = other.MessageId;
    }
    if (other.Timestamp.Length != 0) {
      Timestamp = other.Timestamp;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Type = input.ReadString();
          break;
        }
        case 16: {
          Version = input.ReadInt32();
          break;
        }
        case 26: {
          CorrelationId = input.ReadString();
          break;
        }
        case 34: {
          OperationId = input.ReadString();
          break;
        }
        case 42: {
          MessageId = input.ReadString();
          break;
        }
        case 50: {
          Timestamp = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Type = input.ReadString();
          break;
        }
        case 16: {
          Version = input.ReadInt32();
          break;
        }
        case 26: {
          CorrelationId = input.ReadString();
          break;
        }
        case 34: {
          OperationId = input.ReadString();
          break;
        }
        case 42: {
          MessageId = input.ReadString();
          break;
        }
        case 50: {
          Timestamp = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code