<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Authors>Adrian Strugala</Authors>
		<Company>SolTechnology</Company>
		<Version>4.0.0-preview.1</Version>
		<Description>Library containing extensions for Confluent Kafka platform</Description>
		<PackageLicenseUrl>https://creativecommons.org/licenses/by-nc-sa/3.0/</PackageLicenseUrl>
		<PackageProjectUrl>https://xabe.net/product/avroconvert/</PackageProjectUrl>
		<RepositoryType>Dependency</RepositoryType>
		<PackageTags>avro communication event bus confluent apache kafka core microservice apache.avro</PackageTags>
		<PackageId>SolTechnology.Avro.Kafka</PackageId>
		<RepositoryUrl>https://github.com/AdrianStrugala/AvroConvert</RepositoryUrl>
		<AssemblyName>SolTechnology.Avro.Kafka</AssemblyName>
		<RootNamespace>SolTechnology.Avro.Kafka</RootNamespace>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Confluent.Kafka" Version="2.*" />
		<PackageReference Include="Confluent.SchemaRegistry" Version="2.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AvroConvert\AvroConvert.csproj" />
	</ItemGroup>

</Project>
