<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Authors>Adrian Strugala</Authors>
    <Company>SolTechnology</Company>
    <Version>4.0.0-preview.1</Version>
    <Description>Library containing functionalities, which enable communication between microservices using Avro data format</Description>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageProjectUrl>https://soltechnology.dev/avroconvert/</PackageProjectUrl>
    <RepositoryType>Dependency</RepositoryType>
    <PackageTags>avro communication http net core microservice apache.avro avro avroConvert </PackageTags>
    <ApplicationIcon />
    <PackageId>SolTechnology.Avro.Http</PackageId>
    <RepositoryUrl>https://github.com/AdrianStrugala/AvroConvert</RepositoryUrl>
    <AssemblyName>SolTechnology.Avro.Http</AssemblyName>
    <RootNamespace>SolTechnology.Avro.Http</RootNamespace>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup>
    <PackageIcon>avroconvert-icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\docs\avroconvert-icon.png" Pack="true" Visible="false" PackagePath="\" />
    <None Include="..\..\LICENSE.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AvroConvert\AvroConvert.csproj" />
  </ItemGroup>

</Project>
